---
arch:
- amd64
- armv7
- aarch64
auth_api: true
backup_exclude:
- '*/*/'
description: LT-ESPHome add-on for intelligently managing all your ESP8266/ESP32 and BEKEN devices
hassio_api: true
host_network: true
image: ghcr.io/tomyone/lt-esphome-hassio-{arch}
ingress: true
ingress_port: 0
init: false
map:
- ssl:ro
- config:rw
name: LT-ESPHome
panel_icon: mdi:chip
ports:
  6053/tcp: null
ports_description:
  6053/tcp: Web interface (not required for Home Assistant ingress)
schema:
  certfile: str?
  default_compile_process_limit: int(1,)?
  keyfile: str?
  leave_front_door_open: bool?
  relative_url: str?
  ssl: bool?
  status_use_ping: bool?
  streamer_mode: bool?
slug: lt-esphome
uart: true
url: https://docs.libretuya.ml/docs/projects/esphome/
version: 2023.02-1
